spring.application.name=ms-turno
server.port=8088

# Conexión directa a la red de Docker Compose
spring.datasource.url=jdbc:mysql://${DB_HOST:db_turno}:3306/db_turno?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

usuarios.service.url=${USUARIOS_URL:http://ms-usuario:8080/api/v1/usuarios}