spring.application.name=ms-codigoqr
server.port=8087

spring.datasource.url=jdbc:mysql://${DB_HOST:db_qr}:3306/db_qr?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

usuarios.service.url=${USUARIOS_URL:http://ms-usuario:8080/api/v1/usuarios}